### ISSUE TITLE
CP17 remaining cards

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#118] opened 2017-05-12 05:18 UTC
- [x] CP17-002 - Performapal Odd-Eyes Minotaur --ＥＭオッドアイズ・ミノタウロス
- [x] CP17-003 - Performapal Odd-Eyes Dissolver --ＥＭオッドアイズ・ディゾルヴァー
- [x] CP17-004 - Performapal Odd-Eyes Synchron --ＥＭオッドアイズ・シンクロン
- [x] CP17-009 - Superheavy Samurai Helper --超重武者オタス－Ｋ
- [x] CP17-010 - Superheavy Samurai Fist --超重武者コブ－Ｃ
- [x] CP17-012 - Abyss Actor - Curtain Raiser --魔界劇団－カーテン・ライザー
- [x] CP17-014 - Raidraptor - Rudder Strix --ＲＲ－ラダー・ストリクス
- [x] CP17-017 - Twilight Ninja Kagen --黄昏の忍者－カゲン
- [x] CP17-026 - Gladiator Beast Andabatae --剣闘獣アンダバタエ
- [x] CP17-027 - Gladiator Beast Tamer Editor --剣闘獣総監エーディトル
- [x] CP17-029 - Destiny HERO - Duskutopiaguy --Ｄ－ＨＥＲＯ ダスクユートピアガイ

**Comment by EerieCode** [comment] 2017-05-12 07:38
I believe there is a problem with scripting "Performapal Odd-Eyes Synchron": specifically, as you can imagine, the problem is the final effect that Synchro Summons immediately after Special Summoning a monster from the Pendulum Zone. At a first glance, that's the same concept as the Crystrons Tuners: first you Special Summon from somewhere, then you Synchro Summon. The problem is that, as far as I know, cards in the Pendulum Zone are hardcoded so that they can never be Synchro Materials: as such, there will never be a monster summonable using Synchron and a card in the Pendulum Zone, and so the effect will never work.
This is basically the same issue we had previously with "Pendulum Fusion" and "Fullmetalfoes Alkahest": the hardcoding in the core prevents us from implementing effects like these. My suggestion would be to completely remove this location-based hardcoding (ideally from Xyz too, at least for consistency, but for Synchro is absolutely needed) and implementing an effect similar to Alkahest's, where we used EFFECT_EXTRA_FUSION_MATERIAL to allow Spells and Traps to be used as materials: this would allow us to implement this and eventual similar effects without having to alter the core every single time. Any thoughts?

**Comment by destdev** [comment] 2017-05-12 16:01
I've tried to create a workaround for the past 3 hours without any success, I give up now >.>
there's only 1 idea left in me, but I don't have time to toy around with that atm ... at the start of a duel, check if any non-tuner pendulum in hand/deck/extra is able to summon any synchro with this card, then create connections... thus checking the ability to sync before becomming a pendulum spell
this doesn't take any extras into account, but should work with the basics ... if anyone wants to try and toy around with this idea, feel free, else I'll do it somewhen on Sunday

**Comment by EerieCode** [comment] 2017-05-13 06:40
Ok, thanks to MLD's suggestion, I've managed to script a working version of the card: at the moment, when checking for Synchron's target, it will use Card.AssumeProperty to treat the card type as the Pendulum monster's original type, thus bypassing the core restrictions. That being said, while the card is currently usable, I'm not entirely sure this solution won't give any issues, so I'd still recommend doing something on the core to really fix this problem (according to Edo, Card.IsCanBeSynchroMaterial at the moment returns false if the card is not a monster, so maybe we could use SynchroType in there and alter that function so that it always returns the original type for cards in the Pendulum Zone? In the end the solution should be similar to the one previously done for Fusions).

**Comment by destdev** [comment] 2017-05-13 07:14
have you tested this?
it doesn't seem to be working for me, I have Clear Wing in the extra and I'm unable to special summon Performapal Odd-Eyes Light Phoenix with thre effect ...
and yes, I've already adjusted the script to work with an old core version and deleted the "special summon fromex" parts

**Comment by EerieCode** [comment] 2017-05-13 07:16
I tested it on a puzzle in Percy's current version. "Odd-Eyes Persona Dragon" in the Pendulum Zone, Synchron on the field: I could activate the effect and Synchro Summon Clear Wing. Has Card.AssumeProperty been changed recently, by chance?

**Comment by destdev** [comment] 2017-05-13 07:35
no idea, either that or I do something seriously wrong...
when was the last time percy has updated the core from fluoro?

**Comment by EerieCode** [comment] 2017-05-13 07:42
Around the end of January, I think? I don't think it has been updated since the release of the last version...

**Comment by destdev** [comment] 2017-05-13 07:53
tbh, no idea what's wrong on my end, we updated last time around the time the cyvers type was implemented... there shouldn't be any difference, I copied your script from the percy repo 1:1 and I also removed the tuner check on line 112, that also made problems when I tested around... well, I'll keep searching for the issue and see what I may find then

**Comment by destdev** [comment] 2017-05-13 08:20
for whatever reason "GetOriginalType()" doesn't seem to work on our end at the Pendulum location, no idea why... may be some kind of fault, caused by reverted updates we had during begin of april or something I guess...

**Comment by destdev** [comment] 2017-05-13 08:40
have you tried that outside of a puzzle?
I got it to work now within a puzzle (instead of original type I just assume Type Monster + Type Pendulum now), however it doesn't work in a LAN duel...
is that a fault of our core again or can anyone confirm that behaviour?

**Comment by EerieCode** [comment] 2017-05-13 09:27
Oddly enough, the same thing happened to me right now: I could use Synchron in a puzzle, but trying the exact same move in an actual Duel didn't work. I guess I'll have to look for another solution...

**Comment by TheOnePharaoh** [comment] 2017-05-14 20:13
https://ygorganization.com/ocg-collectors-pack-2017-rulings/

- [ ] Lancer Dragon cannot activate the effect of an Odd-Eyes Lancer Dragon in your hand that Special Summons itself if a facedown monster was destroyed by an effect while it's facedown.

- [ ] when Mystical Space Typhoon destroys the only Set card in your Spell & Trap Zone, you will have no Set cards, so the effect of Performapal Five-Rainbow Magician that prevents monsters on your field from attacking or activating their effects applies. In that case, the attack of Odd-Eyes Wing Dragon stops. (Damage calculation is not performed.)

- [ ]  when resolving the monster effect of D/D/D Superdoom King Whitest Armageddon, there are no face-up Pendulum Monsters on your opponent’s field. In that case, the effect is not applied. (The effects of Odd-Eyes Lancer Dragon are not negated.)

- [ ] A: If White Moray is Normal Summoned while the effect of Skill Drain is applying, White Moray cannot attack directly this turn with its own effect, even if the effect of Skill Drain later stops applying. Also, if Skill Drain is activated after White Moray is Normal Summoned, White Moray can still attack directly that turn with its effect. `though personally I think that's a bit strange`

- [ ] Even if Amazoness Pet Liger attacks and is destroyed by battle, you can activate its effect after damage calculation.

- [ ] Even if you cannot Special Summon with the effect of Monster Reborn because the targeted monster is no longer in the Graveyard, since Monster Reborn was still activated successfully, the effect of Quiet Life is applied and you cannot Normal Summon for the rest of this turn.

- [ ] Q: Quiet Life is face-up in the Spell & Trap Zone. In this situation, I Special Summon a Dogoran, the Mad Flame Kaiju from my hand to my opponent’s field with its effect. In this case, which player will the effect of Quiet Life be applied to?
 A: In this scenario, the player who Special Summoned Dogoran, the Mad Flame Kaiju is the one who cannot Normal Summon during this turn due to the effect of Quiet Life. (The effect is not applied to your opponent, whose field Dogoran, the Mad Flame Kaiju was Special Summoned to.)

- [ ] If a Vision HERO Witch Raider in your hand is treated as a Level 6 monster by the effect of Cost Down, you can then Tribute Summon it by Tributing 1 Trap Card instead of a monster.

- [ ]  You cannot activate the effect of Vision HERO Witch Raider during the turn you Special Summon a monster in face-down Defense Position. (Even if the monster that you Special Summoned in face-down Defense Position was a “HERO” monster, you cannot activate the effect of Vision HERO Witch Raider.)

- [ ] Even if there are no cards in your opponent’s Graveyard, if your Lazion, the Timelord battled during this Battle Phase, its effect will activate and start a Chain.

- [ ] Q: My Sadion, the Timelord battled during the current Battle Phase. During the End Step of this Battle Phase, my Life Points are 3500, so the effect of Sadion, the Timelord that makes my Life Points become 4000 activates. My opponent chains Smile Universe and Special Summons Odd-Eyes Pendulum Dragon, so that I also gain 2500 Life Points, and they become 6000. In this case, how does the effect of Sadion, the Timelord resolve?
 A: As in this scenario, if your Life Points are higher than 4000 when the effect of Sadion, the Timelord resolves, the effect will still make your Life Points become 4000.

those are the ones that I thought may need script fixes.

- [ ] 

- [ ]

**Closed** 2017-05-19 09:03 UTC
