### ISSUE TITLE
Setcodes for TDIL cards

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#11] opened 2016-02-17 08:30 UTC
Now that a bunch of new cards has been revealed, there are two new setcodes that need to be added. The new "Metalphosis" archetype shouldn't be a problem, according to the strings file the next avaiable code should be 0xe2: the real issue comes with cards like "Magician's Rod" and "Dark Magic Circle", that work on cards that contain "Dark Magician" in their card text. How do we deal with them? Should we make an entirely new setcode (let's say, 0xe3) or use a subcode for "Magician" (like 0x40a2) despite those cards having no "Magician" in their name (ex. "Eye of Timaeus") but being only tangentially related? Any suggestions?

**Comment by mercury233** [comment] 2016-02-17 09:41
https://github.com/Fluorohydride/ygopro-scripts/pull/273
I agree with @nekrozar , let us write it in scripts.

**Comment by EerieCode** [comment] 2016-02-17 09:50
Perfect. Thank you!

**Comment by DailyShana** [comment] 2016-02-21 09:38
The code of new setcards should follow the order of cards in the pack and the sale order of new packs.
This order is trackable and clear and more reasonable than following the announcement in the news.

0xe2 should be the first archetype appeared in the newly released cards.
TDIL will be released in April and maybe new cards released in March will introduce a new archetype.
Also, メタルフォーゼ/Metalphosis cards appear begin at TDIL-021, but we don't know whether there exists new archetype in TDIL-001~020.
I advise using `0x1e2` as a temp setcode for `メタルフォーゼ/Metalphosis`, 0x1e3 for the next new archetype anounced in news and so on.

Using temp setcodes like 0x1XX can also avoid potential conflicts with formal scripts.

**Comment by mercury233** [comment] 2016-02-21 12:11
I don't agree with this view for 2 reasons.
1. Making setcodes fully follow the order of card release won't make any sense.
Nobody should check setcodes order to know the order of release, or the order of cards become series. And if you are looking for the setcode of a series, you should check cards of the series formal released, or use ctrl+f in strings.conf.
What is more, the setcodes aren't in order now.
2. If we use 0xe2 now, we **might** need to change it for some reason, but if we use 0x1e2 now, we **must** change it in the future. I think the former is better.

**Comment by DailyShana** [comment] 2016-02-21 13:03
The order of card release is definite so we can treat it as a protocol then everyone can get the same result if we follow it from now on. In fact, except for the old cards wriitten at the initial stage of ygopro project and some special cases, the newly add setcodes is in order strictly.

Since we already use temp id, why not accept temp setcode. Database must be changed anyway.
Using temp setcode has the advantage that we can keep it until they are formalyl released and do not care about what setcode the formal scripts use, just like using 9-digit id to avoid possible id conflict.
For instance, a new archetype appears in the new pack released in 3.10, we should use 0xe2 in formal scripts(the repositoy of formal scripts should be independent of this project). Then change メタルフォーゼ/Metalphosis to 0xe3. If another new archetype appears in the new pack released in 3.20, we have to change it again.

**Comment by mercury233** [comment] 2016-02-21 13:29
Everyone should follow the setcodes in https://github.com/Fluorohydride/ygopro , don't need to get a setcode on heself.

Less change is better, for example, I don't think we should change existing setcodes eventhough in this situation:
We decided to use 0xe2 for "メタルフォーゼ/Metalphosis".
News say TDIL 010-015 are a new series "Abcd", but no card use "Abcd" as series name for now, and there is a huge possibility for KONAMI to release a Spell which use "Abcd" as series name.
KONAMI use "Qwer" in a new card as series name, and it will be released in 20/3/16.

Then we just use 0xe3 for "Qwer", and might use 0xe4 for "Abcd" in future.

0xe2 for "Qwer" , 0xe3 for "Metalphosis" won't be better than this too much, but it is much more inconvenient for our work.

**Comment by destdev** [comment] 2016-02-21 14:11
You asume for the whole situation the worst case szenario. Ok, we might need to change the setcode several times if that takes place.

Experience however shows us, that this is hardly the case. I can't remember any setcode change in Devpro which was caused by your described szene. If I'd have to guess I'd say we are good to go with the setcodes without needing to change them in about 50% of the times, the others maybe 1 change and that's it, I don't think more changes are necassary most of the time.
It is possible that we have to do more changes at one time or another, but that extra work we have to do there doesn't outweigh the extra work we'd have to do with a pre-setcode that has 0% possibility to be usable later.

**Comment by DailyShana** [comment] 2016-02-21 14:37
@mercury233 
in your case, it is unreasonable to jump a position or record 0xe2 in advance to add "Qwer" as 0xe3 when adding that script to the Fluorohydride/ygopro since ygopro project should be independent of this project.
since you always need to change card id, it don't add much labor to change setcode.

**Comment by StormWulf** [comment] 2016-02-22 21:25
It's not difficult to change setcodes, but it's grind work that most people in this team prefer to avoid, especially for simulators that need to update their datas entries. I agree with @mercury233 that hypothetical scenarios aren't worth extra effort. If the situation occurs where a new setcode is officially released before a setcode that was revealed sooner, then we can make the changes.

**Comment by mercury233** [comment] 2016-04-09 03:12
So as @DailyShana said, let us use

> !setname 0xe1 炼装 メタルフォーゼ Metalphosis
!setname 0xe2 变形金字塔 トラミッド Tramid
!setname 0xe3 方界 Houkai

and  `0x1e4` and so on as other temp setcodes.

Any other ideas?

**Comment by EerieCode** [comment] 2016-04-09 05:04
You know, I've been wanting to ask it for a while: how come we're writing the setcodes directly in the scripts? Wouldn't it be more efficient to use some constants like we do with attribute, categories, etc? This way we would be able to do changes like this by editing only one file, instead of having to alter a ton of unrelated scripts every time.

**Comment by mercury233** [comment] 2016-04-09 05:06
Similar reason like why https://github.com/Fluorohydride/ygopro-scripts/pull/318 is ignored?

**Comment by EerieCode** [comment] 2016-04-09 05:09
I didn't even know there was an issue like that. I don't know, I still think using constants would be better: I don't think rewriting all previous scripts would be feasable, but at least for the unreleased cards, where the setcodes are constantly getting changed, it would make the difference.

**Comment by mercury233** [comment] 2016-04-09 05:12
@DailyShana @salix5 @VanillaSalt what do you think about EerieCode and my suggestion?

**Comment by Zayelion** [comment] 2016-04-09 08:30
> You know, I've been wanting to ask it for a while: how come we're writing the setcodes directly in the scripts? 

I've been wondering this for a while also.

**Comment by salix5** [comment] 2016-04-10 18:11
Attribute and type are basically fixed sets, but setcode is not.
Since setcode is related to card names, their English names may be unknown while the card releases, and how to set the name of constants itself will become another problem.

My opinion is that keeping the record in strings.conf and use the current settings.
About the setcode in pre-scripts, maybe you can start from another place like 0x100 instead?

@mercury233 
我沒有刻意忽略Fluorohydride/ygopro-scripts#318，只是我自己現在的時間也不多，我只能優先檢查直接影響到效果處理的腳本。

**Closed** 2016-04-13 16:09 UTC
